version: "3"
services:
  postgres:
    container_name: postgresStock
    image: postgres:latest
    ports:
      - "3232:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadminStock
    image: dpage/pgadmin4
    ports:
      - "7070:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
